<?php
    $_products = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

<div id="mosaic_container">
    <?php foreach($_products as $_product): ?>
        <div class="box col<?php echo rand(1, 3) ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(500); ?>" />
        </div>
    <?php endforeach ?>
</div>


<script type="text/javascript">
    var largeSize="680px";
    $j(function() {
        $j('#mosaic_container').masonry({
            itemSelector: '.box',
            columnWidth: 100,
            isAnimated: true
//            animationOptions: {
//                complete: function() {
//                    if ($j(this).hasClass('clicked')) {
//                        $j(this).width
//                        $j(this).find('img').animate({width: largeSize, height: largeSize}, 1000, function() {
//                        });
//                        $j(this).animate({width: largeSize, height: largeSize}, 1000, function() {
//                            $j('#mosaic_container').masonry('reload');
//                        });
//                        $j(this).removeClass('clicked');
//                    }
//                }
//            }
        });

        $j('#mosaic_container .box').click(function() {
            $j('#mosaic_container .box').css({width: '', height: '', zIndex: ''});
            $j('#mosaic_container .box').css({width: '', height: '', zIndex: ''});
            $j('#mosaic_container .box img').css({width: '', height: ''});
            $j(this).css({zIndex: 999})
            $j(this).addClass('clicked');
//            $j(this).animate({width: largeSize, height: largeSize}, 1000, function() {
                $j('#mosaic_container .box').first().before(this);
                $j('#mosaic_container').masonry('reload');
//            })
//            $j(this).find('img').animate({width: largeSize, height: largeSize}, 1000);
//            $j('#mosaic_container').masonry('reload');
        })
    })
</script>