<?php
    $_products = $this->getLoadedProductCollection();
    $_coreHelper = $this->helper('core');
    $_taxHelper = $this->helper('tax');
?>
<div id="nav-tab">
    <a href="#">Filter</a>
</div>
<div id="mosaic_container">
    <div class="box col5">
        <h1 class="mosaic-title"><?php echo Mage::getStoreConfig('general/store_information/name') ?></h1>
    </div>
    <?php foreach($_products as $_product): ?>
        <div class="box col<?php echo $_product->getBestsellerGroup() ?>">
            <div class="box-inner">
                <div class="face box-front">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(500); ?>" />
                    <div style="display:none" class="summary">
                        <div class="summary-left">
                            <p class="product-name"><?php echo $_product->getName() ?></p>
                            <p><?php echo $_coreHelper->currency($_taxHelper->getPrice($_product, $_product->getFinalPrice(), true)) ?></p>
                        </div>
                        <div class="summary-right">
                            <a href="#" class="more-info" onclick="return false;">i</a>
                        </div>
                    </div>
                </div>
                <div class="face box-back">
                    <div class="details">
                        <p><?php echo $_product->getShortDescription() ?></p>
                        <a href="#" class="button green bigrounded">Add to Basket</a>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>

<script type="text/javascript">
    $j(function() {

        $j("#nav-tab").click(function () {
            $j('#layered-nav').slideToggle();
            $j('#nav-tab').toggleClass('active');

            if($j('#nav-tab a').text() == "Filter") {
                $j('#nav-tab a').text("Close x");
            } else {
                $j('#nav-tab a').text("Filter");
            }

            return false;
        })


        $j('#mosaic_container').masonry({
            itemSelector: '.box',
            columnWidth: 100,
            isAnimated: true
        });

        $j('#mosaic_container .box').click(function() {

            $j('#mosaic_container .box').removeClass('expanded');
            $j('#mosaic_container .box').css({zIndex: ''});
            $j('#mosaic_container .box .summary').hide();


            $j(this).addClass('expanded');

            this.addEventListener( 'webkitTransitionEnd',
                function( event ) {
                    if($j(this).hasClass('expanded')) {
                        $j(this).find('.summary').slideDown(500);
                        $j('#mosaic_container').masonry('reload');
                    }
                }
            );

            $j(this).css({zIndex: 200});

            this.removeEventListener('webketTransitionEnd');

        });


        $j('#mosaic_container .more-info').click(function() {
            $j(this).parents('.box-inner').addClass('flipped').mouseleave(function(){
                $j(this).removeClass('flipped');
            });
            return false;
        });


        var currentPage=<?php echo $this->getRequest()->getParam('p', 1) ?>;
        var loadingPage=false;
        var lastPage = <?php echo $this->getLoadedProductCollection()->setPageSize(Meanbee_Mosaic_Block_Product_List_Mosaic::PAGE_SIZE)->getLastPageNumber(); ?>

        $j(window).scroll(function() {
            if ($j('body').height() <= ($j(window).height() + $j(window).scrollTop()) && !loadingPage && currentPage < lastPage) {
                // load more
                loadingPage = true;
                $j.ajax({
                    url: '<?php echo Mage::getBaseUrl() . 'mosaic/ajax/category/' ?>',
                    dataType: 'json',
                    data: {p: ++currentPage},
                    success: function(data) {
                        var boxes = $j(data.content.block).find('.box');
                        loadingPage = false;
                        // Chop out the title;
                        boxes.splice(0, 1)
                        $j('#mosaic_container').append(boxes).masonry('appended',boxes);

                    }
                });
            }
        });

    });
</script>